### ISSUE TITLE
Evaluation results issues

### ISSUE THREAD

**Issue by shuyansy** [Vision-CAIR/MiniGPT4-video#18]
Hi~ Thanks for the great work! I want to reproduce the result of Mistral-7b weight, but the results produced by me is lower than the  one reported in the paper. Do you have any ideas?  (test in Msvd without subtitles)
![截屏2024-05-03 下午2 35 39](https://github.com/Vision-CAIR/MiniGPT4-video/assets/50947689/56660221-fd77-45f4-9224-36cb53c84de1)

**Comment by KerolosAtef** [comment]
hello @shuyansy 
Thank you for your interest in our work , 
To get the same results you should use the best checkpoint as mentioned in the readme file : 
[Llama2](https://huggingface.co/Vision-CAIR/MiniGPT4-Video/blob/main/checkpoints/video_llama_checkpoint_best.pth) [Mistral](https://huggingface.co/Vision-CAIR/MiniGPT4-Video/blob/main/checkpoints/video_mistral_checkpoint_best.pth)<br> 
I fixed the URLs bug , and now it opens

and by the way this is my results file with mistral  :
[mistral_best_msvd_no_subtitles.json](https://github.com/Vision-CAIR/MiniGPT4-video/files/15245691/mistral_best_msvd_no_subtitles.json)


I evaluated it again and this is the results (it is better than the reported one in the paper) it depends on some ChatGPT randomness but the changes are in range of about1 % : 
![image](https://github.com/Vision-CAIR/MiniGPT4-video/assets/26412108/2fdaca54-c671-45f6-9ea9-de044dc8f4d0)
