### ISSUE TITLE
Have you tried a small language model, such as Tinylama or phi-2?

### ISSUE THREAD

**Issue by noah003** [Vision-CAIR/MiniGPT4-video#4]
as title described

**Comment by KerolosAtef** [comment]
Hello @noah003 , [tinylama](https://arxiv.org/pdf/2401.02385.pdf) and [phi-2](https://huggingface.co/microsoft/phi-2/discussions/24) both of them have context window of 2048 which is not a good idea to try for videos as in videos we need to have a large context window to accept more frames. 
We tried llama 2 with context window 4096 and this accepts 45 frames, and mistral 8192 and this accept 90 frames (you can the details here in implementation details [MiniGPT4-video](https://arxiv.org/abs/2404.03413)).
You can try  tinylama and phi-2 to be efficient in the number of parameters and fast but this will lead to sample only 22 frames from each video which will lead to lose more information.

I suggest if you want to change the LLM you can try one with larger context window to accept more frames, but you should take care of memory limits while training.

**Comment by noah003** [comment]
> Hello @noah003 , [tinylama](https://arxiv.org/pdf/2401.02385.pdf) and [phi-2](https://huggingface.co/microsoft/phi-2/discussions/24) both of them have context window of 2048 which is not a good idea to try for videos as in videos we need to have a large context window to accept more frames. We tried llama 2 with context window 4096 and this accepts 45 frames, and mistral 8192 and this accept 90 frames (you can the details here in implementation details [MiniGPT4-video](https://arxiv.org/abs/2404.03413)). You can try tinylama and phi-2 to be efficient in the number of parameters and fast but this will lead to sample only 22 frames from each video which will lead to lose more information.
> 
> I suggest if you want to change the LLM you can try one with larger context window to accept more frames, but you should take care of memory limits while training.

Thanks for your answer
